
export class Illustya {
  static FILE_NAME_LIST = [
  './img/illustya/cooking_agodashi.png',
  './img/illustya/junk_kikai.png',
  './img/illustya/fish_sakana_iwashi.png',
  './img/illustya/food_fish_kirimi_red.png',
  './img/illustya/yumiya.png',
  './img/illustya/snorkel_goods.png',
  './img/illustya/fish_shark.png',
  './img/illustya/fish_fugu2.png',
  './img/illustya/fish_kagokakidai.png',
  './img/illustya/darts_ya.png',
  './img/illustya/buki_yari.png',
  './img/illustya/fish_tai.png',
  './img/illustya/yumiya_bowgun.png',
  './img/illustya/snorkel_fin.png',
  './img/illustya/fish_salmon.png',
  './img/illustya/snorkel_goggle.png',
  './img/illustya/fish_pirarucu2.png',
  './img/illustya/tsuyu_mark09_ame.png',
  './img/illustya/fish_maguro2.png',
  './img/illustya/alohashirt_gray.png',
  './img/illustya/fish_hokke.png',
  './img/illustya/fishing_tsurizao_nobezao.png',
  './img/illustya/mushi_mushitoriami.png',
  './img/illustya/denryoku_mark.png',
  './img/illustya/rain_kasa_red.png',
  './img/illustya/fish_sakana_sanma.png',
  './img/illustya/fish_mola2.png',
  './img/illustya/animal_shachi_killer_whale.png',
  './img/illustya/tree_ryuuboku.png',
  './img/illustya/heart_blur.png',
  './img/illustya/fish_sakana_sake.png',
  './img/illustya/shinkai_chouchinankou.png',
  './img/illustya/feather_red.png',
  './img/illustya/mark_face_laugh.png',
  './img/illustya/war_trident.png',
  './img/illustya/yurei_youngwoman3_sad.png',
  './img/illustya/text_mu.png',
  './img/illustya/fish_tobiuo2.png',
  './img/illustya/wasyoku_yakizakana.png',
  './img/illustya/boomerang.png',
  './img/illustya/fish_minokasago.png',
  './img/illustya/fish_maguro.png',
  ]
}

