
export class ImgFileName {
  static FILE_NAME_LIST = [
  './img/wind_effect.png',
  './img/ship_frame.png',
  './img/ship_floor.png',
  './img/dry_lack.png',
  './img/fish_fin.png',
  './img/cloud.png',
  './img/laser_turret.png',
  './img/mortor.png',
  './img/machine_gun.png',
  './img/air_cannon.png',
  './img/mast_close.png',
  './img/mast_open.png',
  './img/spring_green.png',
  './img/spring_red.png',
  './img/air_ball.png',
  './img/bullet_arrow.png',
  './img/ladder.png',
  './img/catapult.png',
  './img/catapult_bullet.png',
  './img/catapult_ammo.png',
  './img/menu.png',
  './img/batsu.png',
  './img/check.png',
  './img/arrow_up.png',
  './img/arrow_down.png',
  './img/ship_core.png',
  './img/cloud_base.png',
  './img/cloud_border.png',
  './img/cloud_blur.png',
  './img/attack_effect.png',
  './img/ship_floor_stone.png',
  './img/ship_floor_glass.png',
  './img/ship_floor_plastic.png',
  './img/ship_floor_bone.png',
  './img/ship_floor_iron.png',
  './img/ship_floor_silver.png',
//  './img/.png',
  './img/ikada.png'
  ]
}
